version: "3.1"

services:
  brscan-container:
    build: .
    image: brscan-image
    container_name: brscan-container
    environment:
      - NAME=Scanner
      - MODEL=MFC-L2710DW
      - IPADDRESS=192.168.1.41
    volumes:
      - /mnt/tank/general/scans/unprocessed:/scans
      - /var/brscans:/var/brscans
      - /var/log:/var/log
    network_mode: host
    restart: always
